const tokens = [
  { name: "AKT", id: "akash-network", tag: "Akash Network (AKT)", category: "Project Tokens" },
  { name: "ANKR", id: "ankr", tag: "Ankr (ANKR)", category: "Project Tokens" },
  { name: "ASTRO", id: "astroport-fi", tag: "Astroport (ASTRO)", category: "Project Tokens" },
  { name: "AXL", id: "axelar", tag: "Axelar (AXL)", category: "Project Tokens" },
  { name: "axlWBTC", id: "axlwbtc", tag: "Axelar BTC (axlWBTC)", category: "Bridget Tokens" },
  { name: "axlWETH", id: "axlweth", tag: "Axelar ETH (axlWETH)", category: "Bridget Tokens" },
  { name: "AXLUSDC", id: "axlusdc", tag: "Axelar USDC (axlUSDC)", category: "Stablecoins" },
  { name: "BAND", id: "band-protocol", tag: "Band Protocol (BAND)", category: "Project Tokens" },
  { name: "BLD", id: "agoric", tag: "Agoric (BLD)", category: "Project Tokens" },
  { name: "CMDX", id: "comdex", tag: "Comdex (CMDX)", category: "Project Tokens" },
  { name: "CRO", id: "crypto-com-chain", tag: "Crypto.com (CRO)", category: "Project Tokens" },
  { name: "ATOM", id: "cosmos", tag: "Cosmos (ATOM)", category: "Project Tokens" },
  { name: "EVMOS", id: "evmos", tag: "Evmos (EVMOS)", category: "Project Tokens" },
  { name: "HUAHUA", id: "chihuahua-token", tag: "Chihuahua (HUAHUA)", category: "Project Tokens" },
  { name: "INJ", id: "injective-protocol", tag: "Injective Protocol (INJ)", category: "Project Tokens" },
  { name: "ION", id: "ion", tag: "Ion (ION)", category: "Project Tokens" },
  { name: "IRIS", id: "iris-network", tag: "IRISnet (IRIS)", category: "Project Tokens" },
  { name: "JUNO", id: "juno-network", tag: "Juno Network (JUNO)", category: "Project Tokens" },
  { name: "KAVA", id: "kava", tag: "Kava (KAVA)", category: "Project Tokens" },
  { name: "KDA", id: "kadena", tag: "Kadena (KDA)", category: "Project Tokens" },
  { name: "LUNC", id: "terra-luna", tag: "Terra Luna (LUNC)", category: "Project Tokens" },
  { name: "LUNA", id: "terra-luna-2", tag: "Terra (LUNA)", category: "Project Tokens" },
  { name: "MARS", id: "mars-protocol-a7fcbcfb-fd61-4017-92f0-7ee9f9cc6da3", tag: "Mars Protocol (MARS)", category: "Project Tokens" },
  { name: "OSMO", id: "osmosis", tag: "Osmosis (OSMO)", category: "Project Tokens" },
  { name: "QCK", id: "quicksilver", tag: "Quicksilver (QCK)", category: "Project Tokens" },
  { name: "REGEN", id: "regen", tag: "Regen Network (REGEN)", category: "Project Tokens" },
  { name: "RUNE", id: "thorchain", tag: "THORChain (RUNE)", category: "Project Tokens" },
  { name: "SCRT", id: "secret", tag: "Secret Network (SCRT)", category: "Project Tokens" },
  { name: "STARS", id: "stargaze", tag: "Stargaze (STARS)", category: "Project Tokens" },
  { name: "STATOM", id: "stride-staked-atom", tag: "Staked ATOM (STATOM)", category: "Liquid Staking" },
  { name: "STJUNO", id: "stride-staked-juno", tag: "Staked JUNO (STJUNO)", category: "Liquid Staking" },
  { name: "STLUNA", id: "stride-staked-luna", tag: "Staked LUNA (STLUNA)", category: "Liquid Staking" },
  { name: "STOSMO", id: "stride-staked-osmo", tag: "Staked OSMO (STOSMO)", category: "Liquid Staking" },
  { name: "STKATOM", id: "stkatom", tag: "Staked ATOM (STKATOM)", category: "Liquid Staking" },
  { name: "STRD", id: "stride", tag: "Stride (STRD)", category: "Project Tokens" },
  { name: "UMEE", id: "umee", tag: "Umee (UMEE)", category: "Project Tokens" },
  { name: "USK", id: "usk", tag: "Kujira USK (USK)", category: "Stablecoins" },
  { name: "CMST", id: "composite", tag: "Composite (CMST)", category: "Stablecoins" },
  { name: "IST", id: "inter-stable-token", tag: "Inter Stable Token (IST)", category: "Stablecoins" },
];

